### ISSUE TITLE
In the memories feature page, "Grade" has two meanings in Chinese and should be parsed separately.

### ISSUE THREAD

**Issue by Dreaminko** [vertesan/hatsuboshi-library#16]
![image](https://github.com/user-attachments/assets/d50ccf01-b29d-4263-8663-7d3f50de5b12)
![image](https://github.com/user-attachments/assets/a4db2146-adbd-4cdb-a234-25ef145ff04e)

**Comment by vertesan** [comment]
Perhaps we can use "Rank" instead, is that acceptable to you?

**Comment by Dreaminko** [comment]
Sounds good.
