### ISSUE TITLE
Could you add a new feature to collect in-game stickers?

### ISSUE THREAD

**Issue by Dreaminko** [vertesan/hatsuboshi-library#19]
![image](https://github.com/user-attachments/assets/650fd62c-2b0c-4318-91b2-0a9a47221046)

There are many character stickers in the game that could be placed on the character introduction page or other sections.

**Comment by vertesan** [comment]
I've also been thinking of refactoring character page these days, I will take your proposal into account.

**Comment by vertesan** [comment]
Feature added in commit c3889f2418edc2886f6bfbf13d66ff44fc4e9c26
